name: YoutubeDownloader 
on:
  push:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check module installs
        shell: pwsh
        run: gci #Import-Module ./YoutubeDownloader/YoutubeDownloader/YoutubeDownloader.psd1
