name: YoutubeDownloader 
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: pwsh

jobs:
  Import-Job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check module imports into Linux
        run: Import-Module ./YoutubeDownloader/YoutubeDownloader.psd1
